### ISSUE TITLE
There is a secret in your pubic code

### ISSUE THREAD

**Issue by wvbe** [OMGitsXupi/HoraPi-Twitter-Bot#1]
File `config.py` contains a few secret codes with which anyone could abuse your Twitter account to post stuff.

Would recommend to either add this file to `.gitignore` (and leave a template/instructions for anyone looking to run your code -- with their own secret), or use environment variables!

Best of luck :)
- Wybe

**Comment by Axgaldo** [comment]
I know thank you! it was a mistake but the secret codes are already changed, and I'm too lazy to change it with environment variables 😂 
Thank you again!
